### PR TITLE
HomeVC - API

### PR DESCRIPTION
**Pull request by at-thanhnguyen4**

### CODE REVIEW

**Comment by at-bienle** [comment]
:+1: There are no linter violations.

**Comment by at-thanhnguyen4** [comment]
Get API for `Header` and `Channel`
Screen Shot 2019-09-05 at 10 00 29

**Comment by at-thanhnguyen4** [comment]
`Home`
Screen Shot 2019-09-05 at 16 48 01

**Comment by at-bienle** [comment]
:+1: There are no linter violations.

**Pull request closed without merging**
